import { useEffect, useState } from 'react'
import { COLORS, demoConstructs, type Construct } from './types'
import { encodeCells, loadConstructs, saveConstruct } from './lib/storage'
type Route = 'home' | 'gallery' | 'create'
const route = (): Route => (window.location.hash.slice(1) as Route) || 'home'
const go = (next: Route) => { window.location.hash = next }
function Logo() { return <button className="logo" onClick={() => go('home')}><span className="logo-mark">×</span> construct atlas</button> }
function Header({ active }: { active: Route }) { return <header><Logo /><nav><button className={active === 'gallery' ? 'active' : ''} onClick={() => go('gallery')}>Explore</button><button className={active === 'create' ? 'active' : ''} onClick={() => go('create')}>Create <span className="arrow">↗</span></button></nav></header> }
function PixelPreview({ cells, large = false }: { cells: number[]; large?: boolean }) { return <div className={`pixel-preview ${large ? 'large' : ''}`}>{cells.map((cell, i) => <i key={i} style={{ background: COLORS[cell].value, opacity: cell === 7 ? 0 : 1 }} />)}</div> }
function App() {
  const [current, setCurrent] = useState<Route>(route()); const [constructs, setConstructs] = useState<Construct[]>(demoConstructs)
  useEffect(() => { const sync = () => setCurrent(route()); window.addEventListener('hashchange', sync); loadConstructs().then(setConstructs); return () => window.removeEventListener('hashchange', sync) }, [])
  return <><Header active={current} />{current === 'home' && <Home />}{current === 'gallery' && <Gallery constructs={constructs} />}{current === 'create' && <Create onSaved={(newItem) => { setConstructs(items => [newItem, ...items]); go('gallery') }} />}</>
}
function Home() { return <main className="home"><div className="hero-kicker"><span className="status-dot" /> a shared space for small ideas</div><h1>Build something<br /><em>that stays.</em></h1><p className="hero-copy">A quiet atlas of the things we make, one considered cell at a time.</p><button className="button button-dark" onClick={() => go('gallery')}>Enter the atlas <span>↗</span></button><div className="hero-footer"><span>01 / 03</span><span>constructs, collected openly</span><span>scroll to explore ↓</span></div><div className="hero-shape shape-one" /><div className="hero-shape shape-two" /></main> }
function Gallery({ constructs }: { constructs: Construct[] }) { const [selected, setSelected] = useState(0); const item = constructs[selected] ?? constructs[0]; return <main className="gallery"><section className="gallery-intro"><p className="eyebrow">The atlas / 2026</p><h1>Many ways<br /><em>to begin.</em></h1><p>Move freely through the collection; new forms arrive with the next visit.</p><button className="button button-red" onClick={() => go('create')}>Make a construct <span>＋</span></button></section><section className="orbit"><div className="orbit-line" />{constructs.map((construct, i) => <button aria-label={`Select construct ${i + 1}`} key={construct.id} className={`orbit-node node-${i + 1} ${selected === i ? 'selected' : ''}`} onClick={() => setSelected(i)}><PixelPreview cells={construct.cells} /></button>)}<div className="selected-detail"><span className="eyebrow">Selected construct</span><p>{item?.rating.toFixed(1)} / 5</p><span className="detail-mark">↗</span></div></section><div className="gallery-foot"><span>{String(constructs.length).padStart(2, '0')} forms indexed</span><span>loaded on arrival · no live feed</span></div></main> }
function Create({ onSaved }: { onSaved: (item: Construct) => void }) { const [cells, setCells] = useState<number[]>(Array(256).fill(7)); const [color, setColor] = useState(0); const [saving, setSaving] = useState(false); const paint = (index: number) => setCells(current => current.map((value, i) => i === index ? color : value)); const submit = async () => { setSaving(true); const item: Construct = { id: new Date().toISOString(), title: 'Untitled / ' + new Date().toLocaleDateString('en-GB').split('/').join('.'), author: 'anonymous', cells, created_at: new Date().toISOString(), rating: 0 }; await saveConstruct({ ...item, title: `${item.title} · ${encodeCells(cells).slice(0, 6)}` }); setSaving(false); onSaved(item) }; return <main className="create"><section className="create-copy"><p className="eyebrow">New construct / 001</p><h1>A small mark<br /><em>is enough.</em></h1><p>Choose a color, then click the grid to leave your trace.</p><div className="palette">{COLORS.map((entry, i) => <button aria-label={entry.name} title={entry.name} key={entry.name} className={color === i ? 'chosen' : ''} style={{ background: entry.value }} onClick={() => setColor(i)}>{i === 7 && '×'}</button>)}</div><div className="create-actions"><button className="button button-dark" onClick={submit} disabled={saving}>{saving ? 'Sending...' : 'Send to the atlas'} <span>↗</span></button><button className="clear-button" onClick={() => setCells(Array(256).fill(7))}>clear canvas</button></div></section><section className="editor-wrap"><div className="editor-meta"><span>16 × 16</span><span>256 cells / 8 tones</span></div><div className="editor-grid">{cells.map((cell, i) => <button key={i} aria-label={`cell ${i + 1}`} onClick={() => paint(i)} style={{ background: COLORS[cell].value, opacity: cell === 7 ? 0.36 : 1 }} />)}</div><div className="editor-note">your name is not required <span>✳</span></div></section></main> }
export default App